apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: reboot-agent
spec:
  template:
    metadata:
      labels:
        k8s-app: reboot-agent
    spec:
      containers:
      - name: reboot-agent
        image: sjdevosonode02.ehealthinsurance.com/demo-reboot-agent
        command:
        - ./reboot-agent
        - --v=4
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - name: dbus-socket
            readOnly: true
            mountPath: /var/run/dbus/system_bus_socket
      volumes:
        - name: dbus-socket
          hostPath:
            path: /var/run/dbus/system_bus_socket 
            type: ''
