apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reboot-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: reboot-controller
    spec:
      containers:
      - name: reboot-controller
        image: sjdevosonode02.ehealthinsurance.com/demo-reboot-controller
        command:
        - ./reboot-controller
        - --v=4
